//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAdminAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stuntendsCourse
    {
        public int id { get; set; }
        public Nullable<int> id_course { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<double> calification { get; set; }
    
        public virtual course course { get; set; }
        public virtual student student { get; set; }
    }
}
